apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-cluster
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  serviceName: "mysql"  # 指定负载均衡网络 
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      - name: mysql
        image: mysql:8.0.25
        ports:
        - containerPort: 3306
          name: web
        env:
          - name: MY_ROOT_PASSWORD
            value: "123456"
          - name: MY_DATABASE
            value: "db_test"
        volumeMounts:      # stateful set 有状态服务，下面需要卷声明挂载
        - name: mysql-cnf
          mountPath: /etc/mysql/conf.d    
        volumeMounts:
          - name:  mysql-data
          mountPath:  /var/lib/mysql
  volumeClaimTemplate:
  - metadata:
      name: mysql-cnf     # 上面cnf的挂载
      namespace: default
      labels:
        app: mysql-cnf
    spec:
      storageClassName: ""
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20m
  - metadata:
      name: mysql-data     # 上面data的挂载
      namespace: default
      labels:
        app: mysql-data
    spec:
      storageClassName: ""
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
# 为了稳定的网络
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    app: mysql
  type: NodePort
  # type: ClusterIP
  # clusterIP: none # 无头网络 不能通过集群IP访问，只能内部访问 
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306 # service 端口
    targetPort: 3306 # 容器端口 
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.



