apiVersion: v1
kind: Pod
metadata:
  name: "multi-container-pod"
  namespace: default
  labels:
    app: "multi-container-pod"
spec:
  volumes:
    - name: nginx-vol
      emptyDir: {}
  containers:
  - name: nginx-container
    image: "debian-slim:latest"
    volumeMounts:
      - name: nginx-vol
        mountPath: /usr/share/nginx/html
  - name: content-container
    image: "alpine"
    command: ["/bin/sh","-c","while true;do sleep 1; date > ; done;"]
    volumeMounts:
      - name: nginx-vol
        mountPath: /app