apiVersion: v1
kind: Pod
metadata:
  name: "pod-taint"
  namespace: default
  labels:
    app: "pod-taint"
spec:
  containers:
  - name: pod-taint
    image: "debian-slim:latest"
    command: ["sleep","3600"]
  tolerations: 
  - key: "haha"
    effect: "NoSchedule" # 能容忍污点haha，无论值是多少。
