apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis-cache
  namespace: default
  labels:
    app:  redis-cache
spec:
  selector:
    matchLabels:
      app: store
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:  # template里面是pod模版
    metadata:
      labels:
        app:  store
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
        - name: redis-cache
          image: redis:3.2-alpine
      affinity:
        podAntiAffinity: # 符合以下指标的不会调度过去
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions: # 如果按照以下标签找到了pod就不来了
                  - key: app
                    operator: In
                    values:
                    - store
              topologyKeys: "kubernetes.io/hostname"
            # 拓扑键（划分逻辑区域）。node节点以name为拓扑网络（name相同认为是同一个东西）多个看成一个 
            # 亲和就是放在这个逻辑区域，反亲和就是避免放在这个区域
