apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume-10m
  namespace: default
  labels:
    app: pv-volume-10m
spec:
  storageClassName: my-nfs-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10m
  nfs:
    server: 172.21.16.251
    path: /nfs/data/haha

# 通过nfs pv 持久化数据卷的方式将文件挂载到nfs服务器上面 