# secret保存在集群的etcd里面
apiVersion: v1
kind: Pod
metadata:
  name: "pod-secret-volume"
  namespace: default
  labels:
    app: "pod-secret-volume"
spec:
  volumes:  # 指定挂载详情 可以想象这里是容器外面，pod里面 指定的secret 
  - name:  app
    secret: 
      defaultMode: 0777 # 修改默认的权限模式
      secterName: db-user-pass  # 如果不写下面的items 则 db-user-pass里面的所有secret全部挂出来
      items:                    # 如果写了item的话，key 就指定文件 path 则是在下面挂载进去的文件目录下的文件名 
        - key: password.txt
          path: pwd.md
  containers:
  - name: pod-secret-volume
    image: "busybox"
    command: ["/bin/sh","-c","sleep 3600"]  ## echo $My_USR
    resources:
       limits:
         cpu: 10m ###  1核代表1000m
       requests: 
         cpu: 5m
    volumeMounts:
    - name:  app
      mountPath: /app   # 容器内的app文件夹是集群中secret名叫db-user-pass的内容 


