apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  # 所属的名称空间 
  name: pod-reader
rules:
- apiGroups: [""] # "" 标明 core API 组
  resources: ["pods"]   # 指定能操作的资源 能操作该名称空间下的所有pod   
  verbs: ["get", "watch", "list"]